baseURL: 'https://karasfort.github.io/'
languageCode: en-us
title: Kara S. Fort
theme: sans
publishDir: docs
canonifyURLs: false
relativeURLs: false
enableRobotsTXT: true
summaryLength: 50
defaultMarkdownHandler: goldmark
module:
  hugoVersion:
    extended: false
    min: 0.146.0
pagination:
  disableAliases: false
  pagerSize: 10
  path: page
taxonomies:
  author: authors
  category: categories
  tag: tags
markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
        enable: true
  highlight:
    lineNos: true
    lineNumbersInTable: true
    style: monokai
  tableOfContents:
    endLevel: 5
    ordered: false
    startLevel: 2
outputs:
  home:
    - HTML
    - RSS
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
permalinks:
  posts: /:year/:month/:slug/
params:
  custom_css: 
    - "/css/custom.css"
  favicon: 
    - "/favicon.ico"
