---
title: "Teaching"
output: html_document
---

I believe that learning is an iterative process, in which success is only achieved through overcoming numerous challenges and failures. Because of this, I emphasize the importance of fallibility in my classes through the use of low-stakes, scaffolded assignments, activities that require students to learn about and use media literacy, and debate activities that require students to staunchly defend their positions. I also recognize that applying a theoretical lens to an applied and diverse field, such as communication, can be difficult, so I work to provide students opportunities to engage with applied scenarios to work through how theory can inform real-world processes.

{{<text-font size="large">}}
{{<poet>}}
{{<centered>}}
{{<color light="#ba0c2f" dark="#a7b1b7">}}
Courses Taught
{{</color>}}
{{</centered>}}
{{</poet>}}
{{</text-font>}}

I have served as both an independent instructor and as a teaching assistant throughout my time at The Ohio State University. I have taught both online and in-person, across a variety of class sizes. I have been responsible for developing accelerated 8-week versions of courses and supervising graduate student graders.

{{< tabs >}}
title: Independent Instruction
content: 
  - Communication & Decision Making (online, 67 students)
  - Advertising & Society (online, 47 students)
  - Persuasive Communication (in-person, 30 students)
  - Media & Citizenship (online, 188 students)

<!--tab-->
title: Teaching Assistant
content: 
  - Strategic Communication Principles (online, 190 students)
  - Communication & Decision Making (online, 114 students)
  - Advertising & Society (online, 222 students)
  - Social Implications of Communication Technology (online, 96 students)
  - Social Media (online, 79 students)
{{< /tabs >}}

{{<text-font size="large">}}
{{<poet>}}
{{<centered>}}
{{<color light="#ba0c2f" dark="#a7b1b7">}}
Student Feedback
{{</color>}}
{{</centered>}}
{{</poet>}}
{{</text-font>}}

{{< author-quote author="Student 1" source="Persuasion Course" >}}

I have always been scared to mess up or to get the question wrong. If I was not perfect, then I was not good enough. But messing up in life is the only way I can learn and grow into the person that I am supposed to be. This class has helped me understand that. Through our speeches and writings, I was never perfect in them, even after practicing over and over again, but that is what made them good. This class challenged me to do all these things. I am grateful for the experiences I have had during this class this semester. I hope to continue the academic growth that I have had throughout this whole year. I am so appreciative of you as a professor and the effort and dedication you put into this class; I hope to have more professors like you who care about their students and their education.
{{< /author-quote >}}


{{< author-quote author="Student 2" source="Persuasion Course" >}}

"This class challenged me in ways that felt uncomfortable in the moment but were very worth it in the end. I feel as though I’m leaving it as a slightly better student and citizen, which is probably the best thing I can say about a class."
{{< /author-quote >}}

{{< author-quote author="Student 3" source="Media & Citizenship Course" >}}

"As I move forward, the lessons I learned within this class will follow me. They will help me become not only a better citizen, but a much more respectful and responsible person."
{{< /author-quote >}}


{{< author-quote author="Student 4" source="Media & Citizenship Course" >}}

"I liked how many of the prompts from the discussion posts forced me to consider different perspectives on things. It made me question beliefs that I had taken for granted, and in the end, instead of deeming media as good or bad, I was able to learn about its impact and how that depends on how it's used and how people engage with it. The assignments also challenged me to draw parallels between course concepts and real life which helped me see how certain ideas are applied outside of the classroom."
{{< /author-quote >}}


{{< author-quote author="Student 5" source="Persuasion Course" >}}

"I think it’s really easy to leave a class thinking 'when am I going to use any of this?,' and this class helped me find that use in real time. Of all the classes I’ve taken so far at Ohio State, I think this is one of the classes I can confidently say truly contributed to actual personal skill development and will be useful for professional opportunities in the future."
{{< /author-quote >}}
