---
title: "Research"
output: html_document
---

I am a social scientist interested in how and why people believe or like certain evidence or information. I use various methods including experiments, cross-sectional surveys, and panel surveys in my research. I am also trained in more advanced quantitative methods, such as SEM, social network analysis, and psychometrics. My work has received two top paper panel awards at the National Communication Association Conference (Social Cognition Division in 2025, Political Communication Division in 2025).


{{<text-font size="large">}}
{{<poet>}}
{{<centered>}}
{{<color light="#ba0c2f" dark="#a7b1b7">}}
Current Publications
{{</color>}}
{{</centered>}}
{{</poet>}}
{{</text-font>}}

**Fort, K. S.,** Lopez, R., Shulman, H. C., Riggs, E. E., & Cruz Ibarra, J. (in press). The impacts of code-mixing in a cross-cultural narrative: How processing fluency impacts narrative engagement and attitudes toward out-groups. *Communication Research.* [View Article](https://doi.org/10.1177/00936502241287334)

**Fort, K. S.** & Shulman, H. C. (2024). Using a signal detection approach to understand the impacts of processing fluency and efficacy on accuracy in misinformation detection. *Frontiers in Psychology, 15* (Special Issue: Motivation-Based Approaches to Countering Mass-Mediated Misinformation). [View Article](https://doi.org/10.3389/fpsyg.2024.1417910)

{{<text-font size="large">}}
{{<poet>}}
{{<centered>}}
{{<color light="#ba0c2f" dark="#a7b1b7">}}
Work In Progress
{{</color>}}
{{</centered>}}
{{</poet>}}
{{</text-font>}}

**Fort, K. S.**, Bond, R. M., Nisbet, E. C., Garrett, R. K. (under revision). How Individuals Defend Misperceptions: Data from a Panel Survey Over the Course of the 2024 U.S. Presidential Election.

**Fort, K. S.**,  Shulman, H. C., Bond, R. M., Nisbet, E. C., & Garrett, R. K. (submitted). Epistemic Beliefs Predict Truth Detection Ability: Evidence from Three Large-Scale Surveys.

Garrett, R. K., **Fort, K. S.**, Bond, R. M., & Nisbet, E. C. (in preparation). Ideological Differences in Belief of the Gist of Falsehoods. 

Cruz Ibarra, J., **Fort, K. S.,** & Shulman, H. C. (in preparation). A message-based approach to analyzing populist appeals. 

Holbert, L., Rasheed, H., McKeown, M., **Fort, K. S.,** & Tolan, C. (in preparation) A Scoping Review of Intergenerational Political Socialization Data.

{{<text-font size="large">}}
{{<poet>}}
{{<centered>}}
{{<color light="#ba0c2f" dark="#a7b1b7">}}
Conference Presentations
{{</color>}}
{{</centered>}}
{{</poet>}}
{{</text-font>}}

**Fort, K. S.,**  Shulman, H. C., Bond, R. M., Nisbet, E. C., & Garrett, R. K. (2026, November 19 – 22). Epistemic beliefs predict truth detection ability: A signal detection approach. [Conference presentation]. National Communication Association 112th Annual Conference, New Orleans, LA, United States.

**Fort, K. S.** (2026, March 6). How Americans defend political falsehoods: The influence of ideology, information environment, and epistemic beliefs. [Research Forum presentation]. Hayes Graduate Research Forum, Columbus, OH, United States.\
*3rd place poster at the OSU Hayes Forum in the Social & Behavioral Sciences/Education & Human Ecology Section*

**Fort, K. S.,** Bond, R. M., Nisbet, E.C., & Garrett, R. K. (2025, November 19 – 22). Ideological & epistemic differences in misperception justifications during the 2024 U.S. Presidential Election [Conference presentation]. National Communication Association 111th Annual Conference, Denver, CO, United States.\
*Top paper in the Political Communication Division*

Holbert, L., Rasheed, H., McKeown, M., **Fort., K. S,** & Hardy, B. W. (2025, August 7 – 10). Identifying and Developing a Research Agenda to Address Structural Weaknesses in Political Socialization Research. [Conference presentation]. Association for Education in Journalism and Mass Communication 108th Annual Conference, San Francisco, CA, United States.

**Fort, K.S.** (2025, February 28). The impacts of code-mixing in a cross-cultural narrative: How processing fluency impacts narrative engagement and racial attitudes. [Research Forum presentation]. Hayes Graduate Research Forum, Columbus, OH, United States.\
*OSU Hayes Forum Social & Behavioral Sciences Oral Presentation Finalist*

**Fort, K. S.,** Lopez, R., Shulman, H. C., Riggs, E. E., & Cruz-Ibarra, J. (2024, November 20 – 24). The impacts of code-mixing in a cross-cultural narrative: How processing fluency impacts narrative 
engagement and racial attitudes. [Conference presentation]. National Communication Association 110th Annual Conference, New Orleans, LA, United States.\
*Top paper in the Communication & Social Cognition Division*

**Fort, K. S.** (2024, November 20 – 24) The seed-of-truth effect: The role of premise veracity in support for false conclusions. [Conference presentation]. National Communication Association 110th Annual Conference, New Orleans, LA, United States.

**Fort, K. S.** & Garrett, R. K. (2022, November 17 – 20). Ostracism and falsehood endorsement: Is partisan cheerleading to blame? [Conference presentation]. National Communication Association 108th Annual Conference, New Orleans, LA, United States.


{{<text-font size="large">}}
{{<poet>}}
{{<centered>}}
{{<color light="#ba0c2f" dark="#a7b1b7">}}
Dissertation
{{</color>}}
{{</centered>}}
{{</poet>}}
{{</text-font>}}

My dissertation aims to better understand how and why people find certain arguments or evidence persuasive. Specifically, I am interested in how variables such as similarity, expertise, and evidence/argument type interact with individual's epistemic beliefs to influence perceived argument strength and persuasion. In this work, I draw on theories and concepts such as dual process models, processing fluency, narrative engagement and persuasion, and motivated reasoning.